name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build (Go ${{ matrix.go-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: ["1.22.x", "1.23.x", "stable"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Tidy root
        run: go mod tidy

      - name: Build all (root)
        run: go build ./...

      - name: Tidy and build each folder
        run: |
          set -euo pipefail
          for d in */ ; do
            echo "==> $d"
            if [ -f "$d/go.mod" ]; then
              (cd "$d" && go mod tidy)
            fi
            (cd "$d" && go build .)
          done
